### ISSUE TITLE
GameOverlay: Show tile yield in addition to the tiles name

### ISSUE THREAD

**Issue by rhin123** [rhin123/OpenCiv#14]
Instead of just displaying the names of the tiles of the hovered tile. We should also include the tile yield in the text as well. 

Such as:
```Plains, Forest  +2 (Food Icon)```

**Comment by Ev-EE** [comment]
I would like to work on this issue!

**Comment by rhin123** [comment]
> I would like to work on this issue!

Awesome, you are free to do so. If you have any questions regarding setting up the project through eclipse or any other issues let me know.
As for tackling the issue, I figure were going to have to have a list of CustomLabels for the text, and ColoredBackgrounds as the yield icons being displayed for each yield.
